baseURL = "/"
theme = "dot-hugo-documentation-theme"


[params]
primaryColor = "#02007e"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"

[Languages]

  # English Language
  [Languages.en]
  languageName = "En"
  weight = 1
  languageCode = "en-us"
  title = "Doc List"
  dateFormat = "2 January 2006"
  home = "Home"
  logo = "Dot"
  copyright = "The Hugo Documents are copyright © gethugothemes 2018."

    # navigation
    [Languages.en.menu]
    
      [[Languages.en.menu.main]]
        weight = 2
        name = "Faq"
        url = "faq"
        
      [[Languages.en.menu.main]]
        weight = 2
        name = "contact"
        url = "contact"
        
      [[Languages.en.menu.main]]
        weight = 2
        name = "pages"
        url = "pages"
        hasChildren = true

          [[Languages.en.menu.main]]
          parent = "pages"
          name = "Elements"
          url = "elements"
          weight = 1

          [[Languages.en.menu.main]]
          parent = "pages"
          name = "Installation"
          url = "installation"
          weight = 2

          [[Languages.en.menu.main]]
          parent = "pages"
          name = "Billing and Pricing"
          url = "billing-pricing"
          weight = 3

          [[Languages.en.menu.main]]
          parent = "pages"
          name = "Features"
          url = "features"
          weight = 4




    # banner
    [Languages.en.params.banner]
      title = "Support Center & Knowledge base"
      description = "Find advice and answers from our support team fast or get in touch"
      image = "images/banner.jpg"
      placeholder = "Have a question? Just ask here or enter terms"

    # Topics
    [Languages.en.params.topics]
      title = "Find your answer by subject"
    
    # call to action
    [Languages.en.params.cta]
      enable = true
      title = "Didn't find an answer to your question?"
      description = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
      btnText = "contact us"
      btnURL = "contact"

    # contact
    [Languages.en.params.contact]
      title = "Got Any Questions"
      content = "Submit the form and confirm your email address at <a class='text-primary' href='https://formspree.io/'>Formspree</a> Then add the following lines to contact page YAML Front Matter."

    # footer social icon
    [[Languages.en.socialIcon]]
      icon = "ti-facebook"
      linkURL = "#"

    [[Languages.en.socialIcon]]
      icon = "ti-twitter-alt"
      linkURL = "#"
      
    [[Languages.en.socialIcon]]
      icon = "ti-vimeo-alt"
      linkURL = "#"
      
    [[Languages.en.socialIcon]]
      icon = "ti-instagram"
      linkURL = "#"



  # chinese Language
  [Languages.zh]
  languageName = "Zh"
  weight = 1
  languageCode = "zh-cn"
  title = "Doc List"
  dateFormat = "2 January 2006"
  home = "Home"
  logo = "Dot"
  copyright = "The Hugo Documents are copyright © gethugothemes 2018."

    # navigation
    [Languages.zh.menu]
    
      [[Languages.zh.menu.main]]
        weight = 2
        name = "常见问题"
        url = "faq"
        
      [[Languages.zh.menu.main]]
        weight = 2
        name = "联系"
        url = "contact"
        
      [[Languages.zh.menu.main]]
        weight = 2
        name = "内容"
        url = "pages"
        hasChildren = true

          [[Languages.zh.menu.main]]
          parent = "内容"
          name = "Elements"
          url = "elements"
          weight = 1

          [[Languages.zh.menu.main]]
          parent = "内容"
          name = "Installation"
          url = "installation"
          weight = 2

          [[Languages.zh.menu.main]]
          parent = "内容"
          name = "Billing and Pricing"
          url = "billing-pricing"
          weight = 3

          [[Languages.zh.menu.main]]
          parent = "内容"
          name = "Features"
          url = "features"
          weight = 4




    # banner
    [Languages.zh.params.banner]
      title = "知识中心"
      description = ""
      image = "images/banner.jpg"
      placeholder = "有问题，在这里提出来吧"

    # Topics
    [Languages.zh.params.topics]
      title = "以主题查看"
    
    # call to action
    [Languages.zh.params.cta]
      enable = true
      title = "Didn't find an answer to your question?"
      description = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
      btnText = "contact us"
      btnURL = "contact"

    # contact
    [Languages.zh.params.contact]
      title = "Got Any Questions"
      content = "Submit the form and confirm your email address at <a class='text-primary' href='https://formspree.io/'>Formspree</a> Then add the following lines to contact page YAML Front Matter."

    # footer social icon
    [[Languages.zh.socialIcon]]
      icon = "ti-facebook"
      linkURL = "#"

    [[Languages.zh.socialIcon]]
      icon = "ti-twitter-alt"
      linkURL = "#"
      
    [[Languages.zh.socialIcon]]
      icon = "ti-vimeo-alt"
      linkURL = "#"
      
    [[Languages.zh.socialIcon]]
      icon = "ti-instagram"
      linkURL = "#"


